### ISSUE TITLE
Windows | CGameServer::SendClientMessages | Signatures invalid

### ISSUE THREAD

**Issue by fxss-repository** [chrb22/sendvaredit#1]
![image](https://github.com/chrb22/sendvaredit/assets/35665773/779def83-9904-481f-9d24-7381ace23825)
SM & MM updated for latest build;
Windows 10 Pro;
Sendvaredit - latest version;

**Comment by chrb22** [comment]
I've updated the Windows gamedata and got it working again. I re-released v1.0.1 with the changes.
